### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by s-bray** [tretos53/Captive-Portal#10]
Hello! 
I tried out your code on a Raspberry Pi 0, after reboot when I connected to CaptivePortal01 and opened the IP address 192.168.24.1. It showed me 502 Bad Gateway,  nginx.  Is it possible for you to help me out? 

Also,  I believe it couldn't install php7.3-fpm properly on my Raspberry pi 0, is that the source of the problem??

**Comment by 23ewrdtf** [comment]
Hi, I saw that a few days ago but haven't updated the script yet.

- use php7.4 here https://github.com/tretos53/Captive-Portal/blob/master/captiveportal.sh#L96

- update the nginx config with php7.4 https://github.com/tretos53/Captive-Portal/blob/master/default_nginx#L100

**Comment by 23ewrdtf** [comment]
Also I want to mention that php is not really needed for CP to work and I only included it just to have working PHP.
