### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by meoowe** [tretos53/Captive-Portal#11]
I just realized that this uses the same ip address as RaspAP

And i dont want to use it anymore
So do you have a uninstall script???

**Comment by 23ewrdtf** [comment]
Hi @meoowe 

There is no uninstall script. You can check https://github.com/tretos53/Captive-Portal/blob/master/captiveportal.sh for what the script does and remove/change back all the commands.

IP address is specified in https://github.com/tretos53/Captive-Portal/blob/master/dnsmasq.conf and https://github.com/tretos53/Captive-Portal/blob/master/dhcpcd.conf so you can easily change it.

**Comment by meoowe** [comment]
Uhhhh. Ok im just gonna reinstall
