### ISSUE TITLE
Give wifi access

### ISSUE THREAD

**Issue by lucas-it** [tretos53/Captive-Portal#3]
Hello, I installed your software on a raspberry pi, the captive portal is displayed on the connection, but how do I do that when a person clicks on a button or other that is on this page gives him access to wifi? Thank you !

**Comment by 23ewrdtf** [comment]
Hi,
This script was originally used for a project that didn't require the internet, hence this feature was never implemented.
You would have to implemented something like this: `https://andrewwippler.com/2016/03/11/wifi-captive-portal/` or `https://wiki.andybev.com/doku.php?id=using_iptables_and_php_to_create_a_captive_portal` to make it work.

In general the process from above websites is:
1. Client connect to wifi
2. System's firewall script checks if MAC address of the client is in /var/lib/users
3. IF NOT it marks packets from that MAC client as 99 and forwards them to 10.0.0.1
4. IF MAC exists in /var/lib/users then forwards packets to another interface.
You also need another script and php to make it all work.

Sorry for not being more helpful but I would have to spend more time with it to understand and make it work, which I may do in the future.
