### ISSUE TITLE
Samsung popup

### ISSUE THREAD

**Issue by arigus** [tretos53/Captive-Portal#4]
Hi, this is useful scripts. My case is openwrt and uhttpd. i do response using shell. can you explain what is requests was from samsung phones. i checked -http://connectivitycheck.gstatic.com/generate_204
and my responce 302 redirect to my local home index. no popup still
but it seems to be not this. i could not sniff URL URI sending from samsung.
Big thanks!

**Comment by 23ewrdtf** [comment]
Hi,

I'm not android developer so not sure, but according to the source code here: `https://android.googlesource.com/platform/frameworks/base/+/android-7.1.1_r4/services/core/java/com/android/server/connectivity/NetworkMonitor.java` it checks for 

HTTPS: https://www.google.com/generate_204
HTTP: "http://connectivitycheck.gstatic.com/generate_204

Do google search for `site:android.googlesource.com "generate_204" OR "captive"`

If you are using openwrt you can definitely install and run tcpdump. This will show you what Samsung is asking for.

**Comment by arigus** [comment]
Thanks for reply. I tested some samsung, so must be request /responce. Please, share of them.
I could not cupture URI. but i can check there are  http://connectivitycheck.gstatic.com
not sure about generate_204.  I tried responce 302, 204,200 with redirction. no popup yet
Thanks for your time,
