### ISSUE TITLE
We can’t connect to the server at hotspot.localnet.

### ISSUE THREAD

**Issue by akosiramnad** [tretos53/Captive-Portal#9]
Hi good day,

I run your script. but when I connect to the hotspot SSID the browser pops-up with server not found. We can’t connect to the server at hotspot.localnet.
 any idea what am i missing?

Thanks.

**Comment by 23ewrdtf** [comment]
Hi,

What version of raspbian do you use? eg. 2019-09-26-raspbian-buster-lite.zip

Did you check the logs under: /var/log/ and /var/log/nginx?

What's the device you are connecting it to the pie?

**Comment by akosiramnad** [comment]
> Hi,
> 
> What version of raspbian do you use? eg. 2019-09-26-raspbian-buster-lite.zip
> 
> Did you check the logs under: /var/log/ and /var/log/nginx?
> 
> What's the device you are connecting it to the pie?

I'm using ubuntu-18.04.4-preinstalled-server-armhf+raspi3.img
anyway's i solved my problem flashing 2020-05-27-raspios-buster-lite-armhf.img
and run your script.

Thank you.
